apiVersion: v1
kind: Service
metadata:
  name: test-rdi
  namespace: test
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: test-rdi